INSERT INTO produits (categorie, nom, prix, quantite, description, date_creation, date_modification) VALUES 
('moulu', 'Arabica moulu 1', 5, 100, 'Café moulu arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('moulu', 'Arabica moulu 2', 6, 940, 'Café moulu arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('grain', 'Arabica grain 1', 8, 1300, 'Café grain arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('grain', 'Arabica grain 2', 10, 5600, 'Café grain arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('dosette', 'dosette taille 1', 10, 1700, 'Café dosette arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('dosette', 'dosette taille 2', 8, 6900, 'Café dosette arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('grain', 'Arabica grain 3', 15, 7900, 'Café grain arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('grain', 'Arabica grain 4', 13, 1980, 'Café grain arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
('moulu', 'Arabica moulu 3', 5, 100, 'Café moulu arabica', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());